### ISSUE TITLE
BH3Ps

### ISSUE THREAD

**Issue by Mick9555** [keitarogg/BH3-Download-Library#9]
i been trying to add 3601   714    3701 id's but i don't have updated resources  for 7.0 Bata that's just 6.9 Bata 
![image](https://github.com/keitarogg/BH3-Download-Library/assets/103913739/7c82923a-3902-480f-a72f-25a2dc769dae)
![image](https://github.com/keitarogg/BH3-Download-Library/assets/103913739/efbf99a3-6a97-49ad-a2cd-dd604e04a6ed)
Dm me on discord

**Comment by rainbowwarmth** [comment]
我们只提供下载方式，角色数据以崩坏3策划写的数据为准。
